#!/usr/bin/env php
<?php

require_once __DIR__ . "/vendor/autoload.php";

use App\Core\ExecuteCLICommand;

try {
    $command = $argv[1];

    if ( $argv[2] ) {
        throw new Exception( "Wrong Command.\nphp bangu -h to show available commands\n" );
    }

    ExecuteCLICommand::run( $command );

} catch ( \Throwable $e ) {

    printf( "⛔ {$e->getMessage()}" );
}
