#!/usr/bin/env php
<?php
define( "BASE_PATH", __DIR__ );
require_once __DIR__ . "/vendor/autoload.php";

use App\Core\ExecuteCLICommand;

try {

    if ( count( $argv ) !== 2 ) {
        throw new Exception( "Wrong Command.\nphp bangu -h to show available commands\n" );
    }
    [$fileName, $command] = $argv;

    ExecuteCLICommand::run( $command );

} catch ( \Throwable $e ) {

    printf( "⛔ {$e->getMessage()}" );
}
